### PR TITLE
Fix Cordova 9 support

### PR DESCRIPTION
**Pull request by DURK**
Replace `context.requireCordovaModule` with normal `require` where needed.

### CODE REVIEW

**Comment by Bruno361** [comment]
Hello,
Could you please merge this pull request, as it is indeed all that is needed to build with Cordova 9 ?

**Comment by joelchrist** [comment]
@Bruno361 feel free to use the Moreapp:fix/corodova-9 branch for now, as we're doing the same thing.

**Comment by DURK** [comment]
> Hello,
> Could you please merge this pull request, as it is indeed all that is needed to build with Cordova 9 ?

To use this branch, simply set this in your `package.json`:
`"cordova-plugin-deeplinks": "github:MoreApp/cordova-plugin-deeplinks#fix/cordova-9"`

**Comment by Bruno361** [comment]
Thanks to all for your suggestions, I actually already forked the project and use the fixed version. I was going to make the same PR as @DURK and saw that you already suggested the modifications.
It would be nice to have it merged, though, so we can continue to use it through the npm package.

**Comment by shanebdavis** [comment]
I see this has been fixed in version 1.1.1, but 1.1.1 isn't up on npm yet (as-of June 20th 2019). When do you think you'll be able to push it to npm to ease plugin installation? Thanks for the great lib!

**Pull request merged**
